package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetSubType generated by hbm2java
 */
@Entity
@Table(name = "asset_sub_type", catalog = "risk_module")
public class AssetSubType implements java.io.Serializable {

	private Integer assetSubTypeId;
	private Office office;
	private AssetType assetType;
	private String name;
	private Boolean additionalFieldPresent;
	private String description;
	private String multiplierFieldLabel;
	private String additionalFieldLabel;
	private Float annualIncome;
	private Boolean active;
	private String createdBy;
	private String updatedBy;
	private Date createdDate;
	private Date updatedDate;
	private Set<Asset> assets = new HashSet<Asset>(0);

	public AssetSubType() {
	}

	public AssetSubType(Office office, AssetType assetType) {
		this.office = office;
		this.assetType = assetType;
	}

	public AssetSubType(Office office, AssetType assetType, String name,
			Boolean additionalFieldPresent, String description,
			String multiplierFieldLabel, String additionalFieldLabel,
			Float annualIncome, Boolean active, String createdBy,
			String updatedBy, Date createdDate, Date updatedDate,
			Set<Asset> assets) {
		this.office = office;
		this.assetType = assetType;
		this.name = name;
		this.additionalFieldPresent = additionalFieldPresent;
		this.description = description;
		this.multiplierFieldLabel = multiplierFieldLabel;
		this.additionalFieldLabel = additionalFieldLabel;
		this.annualIncome = annualIncome;
		this.active = active;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.assets = assets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "asset_sub_type_id", unique = true, nullable = false)
	public Integer getAssetSubTypeId() {
		return this.assetSubTypeId;
	}

	public void setAssetSubTypeId(Integer assetSubTypeId) {
		this.assetSubTypeId = assetSubTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "office_id", nullable = false)
	public Office getOffice() {
		return this.office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "asset_type_id", nullable = false)
	public AssetType getAssetType() {
		return this.assetType;
	}

	public void setAssetType(AssetType assetType) {
		this.assetType = assetType;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "additional_field_present")
	public Boolean getAdditionalFieldPresent() {
		return this.additionalFieldPresent;
	}

	public void setAdditionalFieldPresent(Boolean additionalFieldPresent) {
		this.additionalFieldPresent = additionalFieldPresent;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "multiplier_field_label", length = 500)
	public String getMultiplierFieldLabel() {
		return this.multiplierFieldLabel;
	}

	public void setMultiplierFieldLabel(String multiplierFieldLabel) {
		this.multiplierFieldLabel = multiplierFieldLabel;
	}

	@Column(name = "additional_field_label", length = 500)
	public String getAdditionalFieldLabel() {
		return this.additionalFieldLabel;
	}

	public void setAdditionalFieldLabel(String additionalFieldLabel) {
		this.additionalFieldLabel = additionalFieldLabel;
	}

	@Column(name = "annual_income", precision = 12, scale = 0)
	public Float getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(Float annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assetSubType")
	public Set<Asset> getAssets() {
		return this.assets;
	}

	public void setAssets(Set<Asset> assets) {
		this.assets = assets;
	}

}
