package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditType generated by hbm2java
 */
@Entity
@Table(name = "audit_type", catalog = "risk_module")
public class AuditType implements java.io.Serializable {

	private Integer auditTypeId;
	private OrgEntity orgEntity;
	private String name;
	private String description;
	private String createdBy;
	private String updatedBy;
	private Date createdDate;
	private Date updatedDate;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<Audit> audits = new HashSet<Audit>(0);
	private Set<AuditTypeScoring> auditTypeScorings = new HashSet<AuditTypeScoring>(
			0);

	public AuditType() {
	}

	public AuditType(OrgEntity orgEntity) {
		this.orgEntity = orgEntity;
	}

	public AuditType(OrgEntity orgEntity, String name, String description,
			String createdBy, String updatedBy, Date createdDate,
			Date updatedDate, Set<Question> questions, Set<Audit> audits,
			Set<AuditTypeScoring> auditTypeScorings) {
		this.orgEntity = orgEntity;
		this.name = name;
		this.description = description;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.questions = questions;
		this.audits = audits;
		this.auditTypeScorings = auditTypeScorings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "audit_type_id", unique = true, nullable = false)
	public Integer getAuditTypeId() {
		return this.auditTypeId;
	}

	public void setAuditTypeId(Integer auditTypeId) {
		this.auditTypeId = auditTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_entity_id", nullable = false)
	public OrgEntity getOrgEntity() {
		return this.orgEntity;
	}

	public void setOrgEntity(OrgEntity orgEntity) {
		this.orgEntity = orgEntity;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auditType")
	@OrderBy("position")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auditType")
	public Set<Audit> getAudits() {
		return this.audits;
	}

	public void setAudits(Set<Audit> audits) {
		this.audits = audits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auditType")
	public Set<AuditTypeScoring> getAuditTypeScorings() {
		return this.auditTypeScorings;
	}

	public void setAuditTypeScorings(Set<AuditTypeScoring> auditTypeScorings) {
		this.auditTypeScorings = auditTypeScorings;
	}

}
