package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuditTypeScoring generated by hbm2java
 */
@Entity
@Table(name = "audit_type_scoring", catalog = "risk_module")
public class AuditTypeScoring implements java.io.Serializable {

	private AuditTypeScoringId id;
	private RatingBucket ratingBucket;
	private AuditType auditType;
	private Integer minScore;
	private Integer maxScore;

	public AuditTypeScoring() {
	}

	public AuditTypeScoring(AuditTypeScoringId id, RatingBucket ratingBucket,
			AuditType auditType) {
		this.id = id;
		this.ratingBucket = ratingBucket;
		this.auditType = auditType;
	}

	public AuditTypeScoring(AuditTypeScoringId id, RatingBucket ratingBucket,
			AuditType auditType, Integer minScore, Integer maxScore) {
		this.id = id;
		this.ratingBucket = ratingBucket;
		this.auditType = auditType;
		this.minScore = minScore;
		this.maxScore = maxScore;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "auditTypeId", column = @Column(name = "audit_type_id", nullable = false)),
			@AttributeOverride(name = "ratingBucketId", column = @Column(name = "rating_bucket_id", nullable = false)) })
	public AuditTypeScoringId getId() {
		return this.id;
	}

	public void setId(AuditTypeScoringId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rating_bucket_id", nullable = false, insertable = false, updatable = false)
	public RatingBucket getRatingBucket() {
		return this.ratingBucket;
	}

	public void setRatingBucket(RatingBucket ratingBucket) {
		this.ratingBucket = ratingBucket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "audit_type_id", nullable = false, insertable = false, updatable = false)
	public AuditType getAuditType() {
		return this.auditType;
	}

	public void setAuditType(AuditType auditType) {
		this.auditType = auditType;
	}

	@Column(name = "min_score")
	public Integer getMinScore() {
		return this.minScore;
	}

	public void setMinScore(Integer minScore) {
		this.minScore = minScore;
	}

	@Column(name = "max_score")
	public Integer getMaxScore() {
		return this.maxScore;
	}

	public void setMaxScore(Integer maxScore) {
		this.maxScore = maxScore;
	}

}
