package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuditTypeScoringId generated by hbm2java
 */
@Embeddable
public class AuditTypeScoringId implements java.io.Serializable {

	private int auditTypeId;
	private int ratingBucketId;

	public AuditTypeScoringId() {
	}

	public AuditTypeScoringId(int auditTypeId, int ratingBucketId) {
		this.auditTypeId = auditTypeId;
		this.ratingBucketId = ratingBucketId;
	}

	@Column(name = "audit_type_id", nullable = false)
	public int getAuditTypeId() {
		return this.auditTypeId;
	}

	public void setAuditTypeId(int auditTypeId) {
		this.auditTypeId = auditTypeId;
	}

	@Column(name = "rating_bucket_id", nullable = false)
	public int getRatingBucketId() {
		return this.ratingBucketId;
	}

	public void setRatingBucketId(int ratingBucketId) {
		this.ratingBucketId = ratingBucketId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditTypeScoringId))
			return false;
		AuditTypeScoringId castOther = (AuditTypeScoringId) other;

		return (this.getAuditTypeId() == castOther.getAuditTypeId())
				&& (this.getRatingBucketId() == castOther.getRatingBucketId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAuditTypeId();
		result = 37 * result + this.getRatingBucketId();
		return result;
	}

}
