package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerFamilyOccupation generated by hbm2java
 */
@Entity
@Table(name = "customer_family_occupation", catalog = "risk_module")
public class CustomerFamilyOccupation implements java.io.Serializable {

	private Integer customerFamilyOccupationId;
	private OccupationSubType occupationSubType;
	private Customer customer;
	private IncomeLumping incomeLumping;
	private Float multiplierValue;
	private String additionalFieldValue;
	private String updatedBy;
	private String createdBy;
	private Date createdDate;
	private Date updatedDate;
	private Boolean active;
	private Float calculatedIncome;
	private Float userDefinedIncome;
	private Boolean multiplierPresent;
	private Set<CustomerFamilyMember> customerFamilyMembers = new HashSet<CustomerFamilyMember>(
			0);

	public CustomerFamilyOccupation() {
	}

	public CustomerFamilyOccupation(OccupationSubType occupationSubType,
			Customer customer) {
		this.occupationSubType = occupationSubType;
		this.customer = customer;
	}

	public CustomerFamilyOccupation(OccupationSubType occupationSubType,
			Customer customer, IncomeLumping incomeLumping,
			Float multiplierValue, String additionalFieldValue,
			String updatedBy, String createdBy, Date createdDate,
			Date updatedDate, Boolean active, Float calculatedIncome,
			Float userDefinedIncome, Boolean multiplierPresent,
			Set<CustomerFamilyMember> customerFamilyMembers) {
		this.occupationSubType = occupationSubType;
		this.customer = customer;
		this.incomeLumping = incomeLumping;
		this.multiplierValue = multiplierValue;
		this.additionalFieldValue = additionalFieldValue;
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.active = active;
		this.calculatedIncome = calculatedIncome;
		this.userDefinedIncome = userDefinedIncome;
		this.multiplierPresent = multiplierPresent;
		this.customerFamilyMembers = customerFamilyMembers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_family_occupation_id", unique = true, nullable = false)
	public Integer getCustomerFamilyOccupationId() {
		return this.customerFamilyOccupationId;
	}

	public void setCustomerFamilyOccupationId(Integer customerFamilyOccupationId) {
		this.customerFamilyOccupationId = customerFamilyOccupationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "occupation_sub_type_id", nullable = false)
	public OccupationSubType getOccupationSubType() {
		return this.occupationSubType;
	}

	public void setOccupationSubType(OccupationSubType occupationSubType) {
		this.occupationSubType = occupationSubType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "income_lumping_id")
	public IncomeLumping getIncomeLumping() {
		return this.incomeLumping;
	}

	public void setIncomeLumping(IncomeLumping incomeLumping) {
		this.incomeLumping = incomeLumping;
	}

	@Column(name = "multiplier_value", precision = 12, scale = 0)
	public Float getMultiplierValue() {
		return this.multiplierValue;
	}

	public void setMultiplierValue(Float multiplierValue) {
		this.multiplierValue = multiplierValue;
	}

	@Column(name = "additional_field_value", length = 500)
	public String getAdditionalFieldValue() {
		return this.additionalFieldValue;
	}

	public void setAdditionalFieldValue(String additionalFieldValue) {
		this.additionalFieldValue = additionalFieldValue;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "calculated_income", precision = 12, scale = 0)
	public Float getCalculatedIncome() {
		return this.calculatedIncome;
	}

	public void setCalculatedIncome(Float calculatedIncome) {
		this.calculatedIncome = calculatedIncome;
	}

	@Column(name = "user_defined_income", precision = 12, scale = 0)
	public Float getUserDefinedIncome() {
		return this.userDefinedIncome;
	}

	public void setUserDefinedIncome(Float userDefinedIncome) {
		this.userDefinedIncome = userDefinedIncome;
	}

	@Column(name = "multiplier_present")
	public Boolean getMultiplierPresent() {
		return this.multiplierPresent;
	}

	public void setMultiplierPresent(Boolean multiplierPresent) {
		this.multiplierPresent = multiplierPresent;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customerFamilyOccupations")
	public Set<CustomerFamilyMember> getCustomerFamilyMembers() {
		return this.customerFamilyMembers;
	}

	public void setCustomerFamilyMembers(
			Set<CustomerFamilyMember> customerFamilyMembers) {
		this.customerFamilyMembers = customerFamilyMembers;
	}

}
