package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etllogs generated by hbm2java
 */
@Entity
@Table(name = "etllogs", catalog = "risk_module")
public class Etllogs implements java.io.Serializable {

	private Integer id;
	private Date createddate;
	private String externalid;
	private String othervalues;
	private String stepname;
	private String reason;

	public Etllogs() {
	}

	public Etllogs(Date createddate, String externalid, String othervalues,
			String stepname, String reason) {
		this.createddate = createddate;
		this.externalid = externalid;
		this.othervalues = othervalues;
		this.stepname = stepname;
		this.reason = reason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createddate", length = 10)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "externalid", length = 150)
	public String getExternalid() {
		return this.externalid;
	}

	public void setExternalid(String externalid) {
		this.externalid = externalid;
	}

	@Column(name = "othervalues", length = 150)
	public String getOthervalues() {
		return this.othervalues;
	}

	public void setOthervalues(String othervalues) {
		this.othervalues = othervalues;
	}

	@Column(name = "stepname", length = 150)
	public String getStepname() {
		return this.stepname;
	}

	public void setStepname(String stepname) {
		this.stepname = stepname;
	}

	@Column(name = "reason", length = 150)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
