package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExternalLoan generated by hbm2java
 */
@Entity
@Table(name = "external_loan", catalog = "risk_module")
public class ExternalLoan implements java.io.Serializable {

	private Integer externalLoanId;
	private ExternalOrganization externalOrganization;
	private Customer customer;
	private String otherOrgName;
	private String status;
	private Float loanAmount;
	private Float pendingAmount;
	private Date effectiveFrom;
	private Date effectiveTo;
	private Date createdDate;
	private Date updatedDate;
	private String createdBy;
	private String updatedBy;
	private Boolean active;

	public ExternalLoan() {
	}

	public ExternalLoan(ExternalOrganization externalOrganization,
			Customer customer) {
		this.externalOrganization = externalOrganization;
		this.customer = customer;
	}

	public ExternalLoan(ExternalOrganization externalOrganization,
			Customer customer, String otherOrgName, String status,
			Float loanAmount, Float pendingAmount, Date effectiveFrom,
			Date effectiveTo, Date createdDate, Date updatedDate,
			String createdBy, String updatedBy, Boolean active) {
		this.externalOrganization = externalOrganization;
		this.customer = customer;
		this.otherOrgName = otherOrgName;
		this.status = status;
		this.loanAmount = loanAmount;
		this.pendingAmount = pendingAmount;
		this.effectiveFrom = effectiveFrom;
		this.effectiveTo = effectiveTo;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "external_loan_id", unique = true, nullable = false)
	public Integer getExternalLoanId() {
		return this.externalLoanId;
	}

	public void setExternalLoanId(Integer externalLoanId) {
		this.externalLoanId = externalLoanId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "external_organization_id", nullable = false)
	public ExternalOrganization getExternalOrganization() {
		return this.externalOrganization;
	}

	public void setExternalOrganization(
			ExternalOrganization externalOrganization) {
		this.externalOrganization = externalOrganization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "other_org_name", length = 45)
	public String getOtherOrgName() {
		return this.otherOrgName;
	}

	public void setOtherOrgName(String otherOrgName) {
		this.otherOrgName = otherOrgName;
	}

	@Column(name = "status", length = 11)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "loan_amount", precision = 12, scale = 0)
	public Float getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(Float loanAmount) {
		this.loanAmount = loanAmount;
	}

	@Column(name = "pending_amount", precision = 12, scale = 0)
	public Float getPendingAmount() {
		return this.pendingAmount;
	}

	public void setPendingAmount(Float pendingAmount) {
		this.pendingAmount = pendingAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_from", length = 10)
	public Date getEffectiveFrom() {
		return this.effectiveFrom;
	}

	public void setEffectiveFrom(Date effectiveFrom) {
		this.effectiveFrom = effectiveFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_to", length = 10)
	public Date getEffectiveTo() {
		return this.effectiveTo;
	}

	public void setEffectiveTo(Date effectiveTo) {
		this.effectiveTo = effectiveTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
