package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExternalOrganization generated by hbm2java
 */
@Entity
@Table(name = "external_organization", catalog = "risk_module")
public class ExternalOrganization implements java.io.Serializable {

	private Integer externalOrganizationId;
	private String name;
	private String description;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String zip;
	private String phoneNumber;
	private String emailAddress;
	private Set<ExternalLoan> externalLoans = new HashSet<ExternalLoan>(0);

	public ExternalOrganization() {
	}

	public ExternalOrganization(String name, String description,
			String addressLine1, String addressLine2, String city,
			String state, String zip, String phoneNumber, String emailAddress,
			Set<ExternalLoan> externalLoans) {
		this.name = name;
		this.description = description;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.externalLoans = externalLoans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "external_organization_id", unique = true, nullable = false)
	public Integer getExternalOrganizationId() {
		return this.externalOrganizationId;
	}

	public void setExternalOrganizationId(Integer externalOrganizationId) {
		this.externalOrganizationId = externalOrganizationId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "address_line1", length = 500)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "address_line2", length = 500)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email_address", length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "externalOrganization")
	public Set<ExternalLoan> getExternalLoans() {
		return this.externalLoans;
	}

	public void setExternalLoans(Set<ExternalLoan> externalLoans) {
		this.externalLoans = externalLoans;
	}

}
