package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IncomeLumping generated by hbm2java
 */
@Entity
@Table(name = "income_lumping", catalog = "risk_module")
public class IncomeLumping implements java.io.Serializable {

	private Integer incomeLumpingId;
	private double jan;
	private double feb;
	private double march;
	private double april;
	private double may;
	private double june;
	private double july;
	private double august;
	private double sept;
	private double october;
	private double nov;
	private double december;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date modifiedDate;
	private Set<CustomerFamilyOccupation> customerFamilyOccupations = new HashSet<CustomerFamilyOccupation>(
			0);
	private Set<Occupation> occupations = new HashSet<Occupation>(0);

	public IncomeLumping() {
	}

	public IncomeLumping(double jan, double feb, double march, double april,
			double may, double june, double july, double august, double sept,
			double october, double nov, double december) {
		this.jan = jan;
		this.feb = feb;
		this.march = march;
		this.april = april;
		this.may = may;
		this.june = june;
		this.july = july;
		this.august = august;
		this.sept = sept;
		this.october = october;
		this.nov = nov;
		this.december = december;
	}

	public IncomeLumping(double jan, double feb, double march, double april,
			double may, double june, double july, double august, double sept,
			double october, double nov, double december, String createdBy,
			Date createdDate, String modifiedBy, Date modifiedDate,
			Set<CustomerFamilyOccupation> customerFamilyOccupations,
			Set<Occupation> occupations) {
		this.jan = jan;
		this.feb = feb;
		this.march = march;
		this.april = april;
		this.may = may;
		this.june = june;
		this.july = july;
		this.august = august;
		this.sept = sept;
		this.october = october;
		this.nov = nov;
		this.december = december;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.customerFamilyOccupations = customerFamilyOccupations;
		this.occupations = occupations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "income_lumping_id", unique = true, nullable = false)
	public Integer getIncomeLumpingId() {
		return this.incomeLumpingId;
	}

	public void setIncomeLumpingId(Integer incomeLumpingId) {
		this.incomeLumpingId = incomeLumpingId;
	}

	@Column(name = "jan", nullable = false, precision = 22, scale = 0)
	public double getJan() {
		return this.jan;
	}

	public void setJan(double jan) {
		this.jan = jan;
	}

	@Column(name = "feb", nullable = false, precision = 22, scale = 0)
	public double getFeb() {
		return this.feb;
	}

	public void setFeb(double feb) {
		this.feb = feb;
	}

	@Column(name = "march", nullable = false, precision = 22, scale = 0)
	public double getMarch() {
		return this.march;
	}

	public void setMarch(double march) {
		this.march = march;
	}

	@Column(name = "april", nullable = false, precision = 22, scale = 0)
	public double getApril() {
		return this.april;
	}

	public void setApril(double april) {
		this.april = april;
	}

	@Column(name = "may", nullable = false, precision = 22, scale = 0)
	public double getMay() {
		return this.may;
	}

	public void setMay(double may) {
		this.may = may;
	}

	@Column(name = "june", nullable = false, precision = 22, scale = 0)
	public double getJune() {
		return this.june;
	}

	public void setJune(double june) {
		this.june = june;
	}

	@Column(name = "july", nullable = false, precision = 22, scale = 0)
	public double getJuly() {
		return this.july;
	}

	public void setJuly(double july) {
		this.july = july;
	}

	@Column(name = "august", nullable = false, precision = 22, scale = 0)
	public double getAugust() {
		return this.august;
	}

	public void setAugust(double august) {
		this.august = august;
	}

	@Column(name = "sept", nullable = false, precision = 22, scale = 0)
	public double getSept() {
		return this.sept;
	}

	public void setSept(double sept) {
		this.sept = sept;
	}

	@Column(name = "october", nullable = false, precision = 22, scale = 0)
	public double getOctober() {
		return this.october;
	}

	public void setOctober(double october) {
		this.october = october;
	}

	@Column(name = "nov", nullable = false, precision = 22, scale = 0)
	public double getNov() {
		return this.nov;
	}

	public void setNov(double nov) {
		this.nov = nov;
	}

	@Column(name = "december", nullable = false, precision = 22, scale = 0)
	public double getDecember() {
		return this.december;
	}

	public void setDecember(double december) {
		this.december = december;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "incomeLumping")
	public Set<CustomerFamilyOccupation> getCustomerFamilyOccupations() {
		return this.customerFamilyOccupations;
	}

	public void setCustomerFamilyOccupations(
			Set<CustomerFamilyOccupation> customerFamilyOccupations) {
		this.customerFamilyOccupations = customerFamilyOccupations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "incomeLumping")
	public Set<Occupation> getOccupations() {
		return this.occupations;
	}

	public void setOccupations(Set<Occupation> occupations) {
		this.occupations = occupations;
	}

}
