package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LoanProduct generated by hbm2java
 */
@Entity
@Table(name = "loan_product", catalog = "risk_module", uniqueConstraints = @UniqueConstraint(columnNames = "external_id"))
public class LoanProduct implements java.io.Serializable {

	private Integer loanProductId;
	private String productName;
	private String productCode;
	private String description;
	private String externalId;
	private Date createdDate;
	private Date updatedDate;
	private String createdBy;
	private String updatedBy;
	private Set<LoanAccount> loanAccounts = new HashSet<LoanAccount>(0);

	public LoanProduct() {
	}

	public LoanProduct(String productName, String productCode,
			String description, String externalId, Date createdDate,
			Date updatedDate, String createdBy, String updatedBy,
			Set<LoanAccount> loanAccounts) {
		this.productName = productName;
		this.productCode = productCode;
		this.description = description;
		this.externalId = externalId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.loanAccounts = loanAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loan_product_id", unique = true, nullable = false)
	public Integer getLoanProductId() {
		return this.loanProductId;
	}

	public void setLoanProductId(Integer loanProductId) {
		this.loanProductId = loanProductId;
	}

	@Column(name = "product_name", length = 45)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_code", length = 45)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "external_id", unique = true, length = 45)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanProduct")
	public Set<LoanAccount> getLoanAccounts() {
		return this.loanAccounts;
	}

	public void setLoanAccounts(Set<LoanAccount> loanAccounts) {
		this.loanAccounts = loanAccounts;
	}

}
