package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoanUtilizationCheck generated by hbm2java
 */
@Entity
@Table(name = "loan_utilization_check", catalog = "risk_module")
public class LoanUtilizationCheck implements java.io.Serializable {

	private Integer loanUtilizationCheckId;
	private LoanPurpose loanPurposeByLoanPurposeId;
	private LoanPurpose loanPurposeByLoanPurposeId2;
	private LoanPurpose loanPurposeByLoanPurposeId1;
	private LoanAccount loanAccount;
	private Float utilizationPercentage1;
	private Float utilizationPercentage2;
	private Float utilizationPercentage3;
	private String createdBy;
	private Date createdDate;

	public LoanUtilizationCheck() {
	}

	public LoanUtilizationCheck(LoanPurpose loanPurposeByLoanPurposeId,
			LoanAccount loanAccount) {
		this.loanPurposeByLoanPurposeId = loanPurposeByLoanPurposeId;
		this.loanAccount = loanAccount;
	}

	public LoanUtilizationCheck(LoanPurpose loanPurposeByLoanPurposeId,
			LoanPurpose loanPurposeByLoanPurposeId2,
			LoanPurpose loanPurposeByLoanPurposeId1, LoanAccount loanAccount,
			Float utilizationPercentage1, Float utilizationPercentage2,
			Float utilizationPercentage3, String createdBy, Date createdDate) {
		this.loanPurposeByLoanPurposeId = loanPurposeByLoanPurposeId;
		this.loanPurposeByLoanPurposeId2 = loanPurposeByLoanPurposeId2;
		this.loanPurposeByLoanPurposeId1 = loanPurposeByLoanPurposeId1;
		this.loanAccount = loanAccount;
		this.utilizationPercentage1 = utilizationPercentage1;
		this.utilizationPercentage2 = utilizationPercentage2;
		this.utilizationPercentage3 = utilizationPercentage3;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loan_utilization_check_id", unique = true, nullable = false)
	public Integer getLoanUtilizationCheckId() {
		return this.loanUtilizationCheckId;
	}

	public void setLoanUtilizationCheckId(Integer loanUtilizationCheckId) {
		this.loanUtilizationCheckId = loanUtilizationCheckId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loan_purpose_id", nullable = false)
	public LoanPurpose getLoanPurposeByLoanPurposeId() {
		return this.loanPurposeByLoanPurposeId;
	}

	public void setLoanPurposeByLoanPurposeId(
			LoanPurpose loanPurposeByLoanPurposeId) {
		this.loanPurposeByLoanPurposeId = loanPurposeByLoanPurposeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loan_purpose_id_2")
	public LoanPurpose getLoanPurposeByLoanPurposeId2() {
		return this.loanPurposeByLoanPurposeId2;
	}

	public void setLoanPurposeByLoanPurposeId2(
			LoanPurpose loanPurposeByLoanPurposeId2) {
		this.loanPurposeByLoanPurposeId2 = loanPurposeByLoanPurposeId2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loan_purpose_id_1")
	public LoanPurpose getLoanPurposeByLoanPurposeId1() {
		return this.loanPurposeByLoanPurposeId1;
	}

	public void setLoanPurposeByLoanPurposeId1(
			LoanPurpose loanPurposeByLoanPurposeId1) {
		this.loanPurposeByLoanPurposeId1 = loanPurposeByLoanPurposeId1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loan_account_id", nullable = false)
	public LoanAccount getLoanAccount() {
		return this.loanAccount;
	}

	public void setLoanAccount(LoanAccount loanAccount) {
		this.loanAccount = loanAccount;
	}

	@Column(name = "utilization_percentage_1", precision = 12, scale = 0)
	public Float getUtilizationPercentage1() {
		return this.utilizationPercentage1;
	}

	public void setUtilizationPercentage1(Float utilizationPercentage1) {
		this.utilizationPercentage1 = utilizationPercentage1;
	}

	@Column(name = "utilization_percentage_2", precision = 12, scale = 0)
	public Float getUtilizationPercentage2() {
		return this.utilizationPercentage2;
	}

	public void setUtilizationPercentage2(Float utilizationPercentage2) {
		this.utilizationPercentage2 = utilizationPercentage2;
	}

	@Column(name = "utilization_percentage_3", precision = 12, scale = 0)
	public Float getUtilizationPercentage3() {
		return this.utilizationPercentage3;
	}

	public void setUtilizationPercentage3(Float utilizationPercentage3) {
		this.utilizationPercentage3 = utilizationPercentage3;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
