package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MailSender generated by hbm2java
 */
@Entity
@Table(name = "mail_sender", catalog = "risk_module")
public class MailSender implements java.io.Serializable {

	private Integer mailSenderId;
	private String toAddress;
	private String fromAddress;
	private String subject;
	private String body;
	private Boolean deliveryFlag;

	public MailSender() {
	}

	public MailSender(String toAddress, String fromAddress, String subject,
			String body, Boolean deliveryFlag) {
		this.toAddress = toAddress;
		this.fromAddress = fromAddress;
		this.subject = subject;
		this.body = body;
		this.deliveryFlag = deliveryFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mail_sender_id", unique = true, nullable = false)
	public Integer getMailSenderId() {
		return this.mailSenderId;
	}

	public void setMailSenderId(Integer mailSenderId) {
		this.mailSenderId = mailSenderId;
	}

	@Column(name = "to_address", length = 500)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@Column(name = "from_address", length = 45)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "subject", length = 500)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "body")
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "delivery_flag")
	public Boolean getDeliveryFlag() {
		return this.deliveryFlag;
	}

	public void setDeliveryFlag(Boolean deliveryFlag) {
		this.deliveryFlag = deliveryFlag;
	}

}
