package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meeting generated by hbm2java
 */
@Entity
@Table(name = "meeting", catalog = "risk_module")
public class Meeting implements java.io.Serializable {

	private Integer meetingId;
	private Customer customer;
	private Boolean dataCaptured;
	private Integer totalMembers;
	private Integer membersPresent;
	private Date meetingDate;
	private Date createdDate;
	private Date updatedDate;
	private String createdBy;
	private String updatedBy;

	public Meeting() {
	}

	public Meeting(Customer customer) {
		this.customer = customer;
	}

	public Meeting(Customer customer, Boolean dataCaptured,
			Integer totalMembers, Integer membersPresent, Date meetingDate,
			Date createdDate, Date updatedDate, String createdBy,
			String updatedBy) {
		this.customer = customer;
		this.dataCaptured = dataCaptured;
		this.totalMembers = totalMembers;
		this.membersPresent = membersPresent;
		this.meetingDate = meetingDate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "meeting_id", unique = true, nullable = false)
	public Integer getMeetingId() {
		return this.meetingId;
	}

	public void setMeetingId(Integer meetingId) {
		this.meetingId = meetingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "data_captured")
	public Boolean getDataCaptured() {
		return this.dataCaptured;
	}

	public void setDataCaptured(Boolean dataCaptured) {
		this.dataCaptured = dataCaptured;
	}

	@Column(name = "total_members")
	public Integer getTotalMembers() {
		return this.totalMembers;
	}

	public void setTotalMembers(Integer totalMembers) {
		this.totalMembers = totalMembers;
	}

	@Column(name = "members_present")
	public Integer getMembersPresent() {
		return this.membersPresent;
	}

	public void setMembersPresent(Integer membersPresent) {
		this.membersPresent = membersPresent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "meeting_date", length = 10)
	public Date getMeetingDate() {
		return this.meetingDate;
	}

	public void setMeetingDate(Date meetingDate) {
		this.meetingDate = meetingDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
