package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OccupationSubType generated by hbm2java
 */
@Entity
@Table(name = "occupation_sub_type", catalog = "risk_module")
public class OccupationSubType implements java.io.Serializable {

	private Integer occupationSubTypeId;
	private Office office;
	private OccupationType occupationType;
	private String name;
	private String description;
	private Boolean multiplierPresent;
	private Boolean additionalFieldPresent;
	private String multiplierLabel;
	private String additionalFieldLabel;
	private Float annualIncome;
	private Boolean active;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Boolean incomeLumpingRequired;
	private String stabilityFactor;
	private Set<Occupation> occupations = new HashSet<Occupation>(0);
	private Set<CustomerFamilyOccupation> customerFamilyOccupations = new HashSet<CustomerFamilyOccupation>(
			0);

	public OccupationSubType() {
	}

	public OccupationSubType(Office office, OccupationType occupationType) {
		this.office = office;
		this.occupationType = occupationType;
	}

	public OccupationSubType(Office office, OccupationType occupationType,
			String name, String description, Boolean multiplierPresent,
			Boolean additionalFieldPresent, String multiplierLabel,
			String additionalFieldLabel, Float annualIncome, Boolean active,
			String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, Boolean incomeLumpingRequired,
			String stabilityFactor, Set<Occupation> occupations,
			Set<CustomerFamilyOccupation> customerFamilyOccupations) {
		this.office = office;
		this.occupationType = occupationType;
		this.name = name;
		this.description = description;
		this.multiplierPresent = multiplierPresent;
		this.additionalFieldPresent = additionalFieldPresent;
		this.multiplierLabel = multiplierLabel;
		this.additionalFieldLabel = additionalFieldLabel;
		this.annualIncome = annualIncome;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.incomeLumpingRequired = incomeLumpingRequired;
		this.stabilityFactor = stabilityFactor;
		this.occupations = occupations;
		this.customerFamilyOccupations = customerFamilyOccupations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "occupation_sub_type_id", unique = true, nullable = false)
	public Integer getOccupationSubTypeId() {
		return this.occupationSubTypeId;
	}

	public void setOccupationSubTypeId(Integer occupationSubTypeId) {
		this.occupationSubTypeId = occupationSubTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "office_id", nullable = false)
	public Office getOffice() {
		return this.office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "occupation_type_id", nullable = false)
	public OccupationType getOccupationType() {
		return this.occupationType;
	}

	public void setOccupationType(OccupationType occupationType) {
		this.occupationType = occupationType;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "multiplier_present")
	public Boolean getMultiplierPresent() {
		return this.multiplierPresent;
	}

	public void setMultiplierPresent(Boolean multiplierPresent) {
		this.multiplierPresent = multiplierPresent;
	}

	@Column(name = "additional_field_present")
	public Boolean getAdditionalFieldPresent() {
		return this.additionalFieldPresent;
	}

	public void setAdditionalFieldPresent(Boolean additionalFieldPresent) {
		this.additionalFieldPresent = additionalFieldPresent;
	}

	@Column(name = "multiplier_label", length = 500)
	public String getMultiplierLabel() {
		return this.multiplierLabel;
	}

	public void setMultiplierLabel(String multiplierLabel) {
		this.multiplierLabel = multiplierLabel;
	}

	@Column(name = "additional_field_label", length = 500)
	public String getAdditionalFieldLabel() {
		return this.additionalFieldLabel;
	}

	public void setAdditionalFieldLabel(String additionalFieldLabel) {
		this.additionalFieldLabel = additionalFieldLabel;
	}

	@Column(name = "annual_income", precision = 12, scale = 0)
	public Float getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(Float annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "income_lumping_required")
	public Boolean getIncomeLumpingRequired() {
		return this.incomeLumpingRequired;
	}

	public void setIncomeLumpingRequired(Boolean incomeLumpingRequired) {
		this.incomeLumpingRequired = incomeLumpingRequired;
	}

	@Column(name = "stability_factor", length = 6)
	public String getStabilityFactor() {
		return this.stabilityFactor;
	}

	public void setStabilityFactor(String stabilityFactor) {
		this.stabilityFactor = stabilityFactor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "occupationSubType")
	public Set<Occupation> getOccupations() {
		return this.occupations;
	}

	public void setOccupations(Set<Occupation> occupations) {
		this.occupations = occupations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "occupationSubType")
	public Set<CustomerFamilyOccupation> getCustomerFamilyOccupations() {
		return this.customerFamilyOccupations;
	}

	public void setCustomerFamilyOccupations(
			Set<CustomerFamilyOccupation> customerFamilyOccupations) {
		this.customerFamilyOccupations = customerFamilyOccupations;
	}

}
