package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OccupationType generated by hbm2java
 */
@Entity
@Table(name = "occupation_type", catalog = "risk_module")
public class OccupationType implements java.io.Serializable {

	private Integer occupationTypeId;
	private String name;
	private String description;
	private Boolean active;
	private Set<OccupationSubType> occupationSubTypes = new HashSet<OccupationSubType>(
			0);

	public OccupationType() {
	}

	public OccupationType(String name, String description,
			Set<OccupationSubType> occupationSubTypes, Boolean active) {
		this.name = name;
		this.description = description;
		this.occupationSubTypes = occupationSubTypes;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "occupation_type_id", unique = true, nullable = false)
	public Integer getOccupationTypeId() {
		return this.occupationTypeId;
	}

	public void setOccupationTypeId(Integer occupationTypeId) {
		this.occupationTypeId = occupationTypeId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "occupationType")
	public Set<OccupationSubType> getOccupationSubTypes() {
		return this.occupationSubTypes;
	}

	public void setOccupationSubTypes(Set<OccupationSubType> occupationSubTypes) {
		this.occupationSubTypes = occupationSubTypes;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
