package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OfficeType generated by hbm2java
 */
@Entity
@Table(name = "office_type", catalog = "risk_module")
public class OfficeType implements java.io.Serializable {

	private Integer officeTypeId;
	private String name;
	private Set<Office> offices = new HashSet<Office>(0);

	public OfficeType() {
	}

	public OfficeType(String name, Set<Office> offices) {
		this.name = name;
		this.offices = offices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "office_type_id", unique = true, nullable = false)
	public Integer getOfficeTypeId() {
		return this.officeTypeId;
	}

	public void setOfficeTypeId(Integer officeTypeId) {
		this.officeTypeId = officeTypeId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "officeType")
	public Set<Office> getOffices() {
		return this.offices;
	}

	public void setOffices(Set<Office> offices) {
		this.offices = offices;
	}

}
