package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgEntity generated by hbm2java
 */
@Entity
@Table(name = "org_entity", catalog = "risk_module")
public class OrgEntity implements java.io.Serializable {

	private Integer orgEntityId;
	private String name;
	private Set<AuditType> auditTypes = new HashSet<AuditType>(0);

	public OrgEntity() {
	}

	public OrgEntity(String name, Set<AuditType> auditTypes) {
		this.name = name;
		this.auditTypes = auditTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "org_entity_id", unique = true, nullable = false)
	public Integer getOrgEntityId() {
		return this.orgEntityId;
	}

	public void setOrgEntityId(Integer orgEntityId) {
		this.orgEntityId = orgEntityId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgEntity")
	public Set<AuditType> getAuditTypes() {
		return this.auditTypes;
	}

	public void setAuditTypes(Set<AuditType> auditTypes) {
		this.auditTypes = auditTypes;
	}

}
