package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RelationshipType generated by hbm2java
 */
@Entity
@Table(name = "relationship_type", catalog = "risk_module")
public class RelationshipType implements java.io.Serializable {

	private Integer relationshipTypeId;
	private String name;
	private String description;
	private Set<CustomerFamilyMember> customerFamilyMembers = new HashSet<CustomerFamilyMember>(
			0);

	public RelationshipType() {
	}

	public RelationshipType(String name, String description,
			Set<CustomerFamilyMember> customerFamilyMembers) {
		this.name = name;
		this.description = description;
		this.customerFamilyMembers = customerFamilyMembers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "relationship_type_id", unique = true, nullable = false)
	public Integer getRelationshipTypeId() {
		return this.relationshipTypeId;
	}

	public void setRelationshipTypeId(Integer relationshipTypeId) {
		this.relationshipTypeId = relationshipTypeId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relationshipType")
	public Set<CustomerFamilyMember> getCustomerFamilyMembers() {
		return this.customerFamilyMembers;
	}

	public void setCustomerFamilyMembers(
			Set<CustomerFamilyMember> customerFamilyMembers) {
		this.customerFamilyMembers = customerFamilyMembers;
	}

}
