package com.conflux.dal.bo;

// Generated 17 Jan, 2013 8:44:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RiskRatingHistory generated by hbm2java
 */
@Entity
@Table(name = "risk_rating_history", catalog = "risk_module")
public class RiskRatingHistory implements java.io.Serializable {

	private Integer riskRatingHistoryId;
	private Customer customer;
	private String originalRating;
	private String updatedRating;
	private String comment;
	private String createdBy;
	private Date createdDate;

	public RiskRatingHistory() {
	}

	public RiskRatingHistory(Customer customer) {
		this.customer = customer;
	}

	public RiskRatingHistory(Customer customer, String originalRating,
			String updatedRating, String comment, String createdBy,
			Date createdDate) {
		this.customer = customer;
		this.originalRating = originalRating;
		this.updatedRating = updatedRating;
		this.comment = comment;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "risk_rating_history_id", unique = true, nullable = false)
	public Integer getRiskRatingHistoryId() {
		return this.riskRatingHistoryId;
	}

	public void setRiskRatingHistoryId(Integer riskRatingHistoryId) {
		this.riskRatingHistoryId = riskRatingHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "original_rating", length = 45)
	public String getOriginalRating() {
		return this.originalRating;
	}

	public void setOriginalRating(String originalRating) {
		this.originalRating = originalRating;
	}

	@Column(name = "updated_rating", length = 45)
	public String getUpdatedRating() {
		return this.updatedRating;
	}

	public void setUpdatedRating(String updatedRating) {
		this.updatedRating = updatedRating;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
